# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Continuous Integration

on:
  push:
    branches: [ "main", "feature/**/*", "refactor/**/*", "bugfix/**/*", "fix/**/*"] # Triggers on push to specified branches
  pull_request:
    branches: [ "main" ] # Triggers on pull requests to the main branch

jobs:
  build:

    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - uses: actions/checkout@v4 # Checks out the repository
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Sets up the specified .NET version
      with:
        dotnet-version: 9.0.x # Specifies the .NET version to use
    
    - name: Restore dependencies
      run: dotnet restore # Restores the dependencies
    
    - name: Build
      working-directory: ./src # Specifies the working directory
      run: dotnet build --no-restore # Builds the project without restoring dependencies
    
    - name: Test
      working-directory: ./src # Specifies the working directory
      run: dotnet test --no-build --verbosity normal # Runs the tests without building the project
