# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Continuous Integration

on:
  push:
    branches: [ "main", "feature/**/*", "refactor/**/*", "bugfix/**/*", "fix/**/*"] # Triggers on push to specified branches
  pull_request:
    branches: [ "main" ] # Triggers on pull requests to the main branch

jobs:
  build:

    runs-on: ubuntu-latest # Specifies the runner environment

    steps:    
    - name: Install .NET SDK
      run: |
          sudo apt-get update && \
          sudo apt-get upgrade -y 

    - uses: actions/checkout@v4 # Checks out the repository
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Sets up the specified .NET version
      with:
        dotnet-version: 9.0.x # Specifies the .NET version to use

    - name: Update Workloads
      run: | 
        sudo dotnet workload update && \
        sudo dotnet workload install maui && \
        sudo dotnet workload install android && \
        sudo dotnet workload install ios && \
        sudo dotnet workload install aspire  
      
    - name: Restore dependencies
      run: dotnet restore # Restores the dependencies
    
    - name: Build
      run: dotnet build --no-restore # Builds the project without restoring dependencies
